name: nbdev CI

on:
  pull_request:
    branches:
      - main  # or whatever branch you want to target

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.3  # specify your desired Python version

    - name: Clone other repositories
      run: |
        git clone https://github.com/dbt-labs/metricflow.git
        git clone https://github.com/dbt-labs/dbt-core.git
    
    - name: Upgrade setuptools
      run: pip install --upgrade setuptools 

    - name: Clear Python package cache
      run: |
        rm -rf ~/.cache/pip
        rm -rf ./.venv  # If you have a virtual environment
        
    - name: Install dependencies
      run: |
        pip install nbdev
        nbdev_install_hooks

    - name: Run nbdev_test for metricflow
      run: |
        nbdev_test metricflow


    - name: Run nbdev_test for dbt-core
      run: |
        nbdev_test dbt_core

    # Add more steps for additional testing or checks if needed
