name: nbdev CI

on:
  pull_request:
    branches:
      - main  # or whatever branch you want to target

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.3  # specify your desired Python version

    - name: Clone other repositories
      run: |
        git clone https://github.com/dbt-labs/metricflow.git
        git clone https://github.com/dbt-labs/dbt-core.git

    - name: Install dependencies
      run: |
        pip install nbdev
        nbdev_install_hooks

    - name: Test documentation build for metricflow.
      run: |
        cd metricflow
        nbdev_build_docs
        cd ..  # Move back to the root directory before running nbdev_test

    - name: Run nbdev_test for metricflow
      run: |
        nbdev_test metricflow

    - name: Test documentation build for dbt-core
      run: |
        cd dbt-core
        nbdev_build_docs
        cd ..  # Move back to the root directory before running nbdev_test

    - name: Run nbdev_test for dbt-core
      run: |
        nbdev_test dbt_core

    # Add more steps for additional testing or checks if needed
